//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaruz.DataGridViewAutoFilter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avaruz.DataGridViewAutoFilter.lang_ja", typeof(lang_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべて.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブランク.
        /// </summary>
        internal static string blanks {
            get {
                return ResourceManager.GetString("blanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カスタマイズ.
        /// </summary>
        internal static string customize {
            get {
                return ResourceManager.GetString("customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定める.
        /// </summary>
        internal static string determine {
            get {
                return ResourceManager.GetString("determine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィールド名.
        /// </summary>
        internal static string fieldName {
            get {
                return ResourceManager.GetString("fieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語が変更されました.
        /// </summary>
        internal static string languageChanged {
            get {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語を選択してください.
        /// </summary>
        internal static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非空白.
        /// </summary>
        internal static string nonblanks {
            get {
                return ResourceManager.GetString("nonblanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to よし.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 含む.
        /// </summary>
        internal static string operatorContains {
            get {
                return ResourceManager.GetString("operatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等しい.
        /// </summary>
        internal static string operatorEquals {
            get {
                return ResourceManager.GetString("operatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to より大きい.
        /// </summary>
        internal static string operatorGreaterThan {
            get {
                return ResourceManager.GetString("operatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以上.
        /// </summary>
        internal static string operatorGreaterThanEquals {
            get {
                return ResourceManager.GetString("operatorGreaterThanEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未満.
        /// </summary>
        internal static string operatorLessThan {
            get {
                return ResourceManager.GetString("operatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to より小さいか等しい.
        /// </summary>
        internal static string operatorLessThanEquals {
            get {
                return ResourceManager.GetString("operatorLessThanEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 含まない.
        /// </summary>
        internal static string operatorNotContains {
            get {
                return ResourceManager.GetString("operatorNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等しくない.
        /// </summary>
        internal static string operatorNotEquals {
            get {
                return ResourceManager.GetString("operatorNotEquals", resourceCulture);
            }
        }
    }
}
