//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridViewAutoFilter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataGridViewAutoFilter.lang_ru", typeof(lang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to весь.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заготовки.
        /// </summary>
        internal static string blanks {
            get {
                return ResourceManager.GetString("blanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to настроить.
        /// </summary>
        internal static string customize {
            get {
                return ResourceManager.GetString("customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определить.
        /// </summary>
        internal static string determine {
            get {
                return ResourceManager.GetString("determine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя поля.
        /// </summary>
        internal static string fieldName {
            get {
                return ResourceManager.GetString("fieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  язык изменен.
        /// </summary>
        internal static string languageChanged {
            get {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        internal static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не пробелы.
        /// </summary>
        internal static string nonblanks {
            get {
                return ResourceManager.GetString("nonblanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ладно.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to содержит.
        /// </summary>
        internal static string operatorContains {
            get {
                return ResourceManager.GetString("operatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to быть равным.
        /// </summary>
        internal static string operatorEquals {
            get {
                return ResourceManager.GetString("operatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лучше чем.
        /// </summary>
        internal static string operatorGreaterThan {
            get {
                return ResourceManager.GetString("operatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше, чем равно.
        /// </summary>
        internal static string operatorGreaterThanEquals {
            get {
                return ResourceManager.GetString("operatorGreaterThanEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше, чем.
        /// </summary>
        internal static string operatorLessThan {
            get {
                return ResourceManager.GetString("operatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше, чем равно.
        /// </summary>
        internal static string operatorLessThanEquals {
            get {
                return ResourceManager.GetString("operatorLessThanEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не содержит.
        /// </summary>
        internal static string operatorNotContains {
            get {
                return ResourceManager.GetString("operatorNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не равно.
        /// </summary>
        internal static string operatorNotEquals {
            get {
                return ResourceManager.GetString("operatorNotEquals", resourceCulture);
            }
        }
    }
}
